### ISSUE TITLE
Package dependency issues

### ISSUE THREAD

**Issue by th-blitz** [cispa/xs-observations#1]
Hi, 

Hope you are doing well,

I am trying to reproduce the xs-leaks experiment, specifically the tbf and facing 2 issues with the setup : 

(A) pyqt5-qt5 dependency issue with `poetry install` and
(B) playwright@1.18.1 installation stuck with `npm install --verbose`  

I am kindly reaching out for your guidance so I may reproduce your work Or you could provide me a containerized version of the work for my convenience, either way I would highly appreciate it.

Please note, I have attached screenshots of the issues for your reference below.

Thanks,
Preetham 

<img width="885" alt="Screenshot 2024-12-09 at 4 49 36 PM" src="https://github.com/user-attachments/assets/6b85407c-80be-4b88-b171-5e3b039ee948">
<img width="923" alt="Screenshot 2024-12-09 at 4 48 23 PM" src="https://github.com/user-attachments/assets/c9d8c473-1691-4568-95e5-6d161a1d4ba8">

**Comment by JannisBush** [comment]
Hi Preetham,

Thanks for your interest in the project.

The `poetry install` error seems to be caused by the fact that some packages are not available (anymore) on some platforms. Luckily, it seems like these dependencies where not used in the final version of the code, so I simply removed them from the installation file and pushed the new installation files: 066bffe
Your screenshot also seems to indicate that you are using python3.13, however, the `pyproject.toml` requires python 3.9.6. (It might be possible to update to a new python version, however, some libraries might be incompatible or not available).

The `npm install` stall could stem from an incompatible node.js version. With node 17, the playwright installation works for me both locally and in Docker. Keep in mind though that this command will install old browser versions, if you do not want to exactly reproduce the experiments from the paper but instead run the tool on new browsers, I would make sense to update the dependencies in `package.json`

I created a Dockerfile where both `poetry install` and `npm install` work. This Dockerfile is however not complete yet, as e.g., the database is missing and some of the code would also require a display/Xvfb. Thus, I would suggest running the pipeline locally and hope the installation now works.

`Dockerfile`:
```Dockerfile
# Stage 1: Python environment
FROM python:3.9.6-slim AS python-build

# Install depedencies
RUN apt-get update && apt-get install -y gcc build-essential libpq-dev

# Install Poetry
RUN pip install poetry

# Set the working directory
WORKDIR /app

# Copy Python project files
COPY . /app

# Install Python dependencies
RUN poetry install

# Stage 2: Node.js environment
FROM node:17 AS node-build

# Copy the python build
COPY --from=python-build / /

# Set the working directory
WORKDIR /app/automator

# Copy Node.js project files (only necessary files for npm install)
COPY ./automator/package*.json ./

# Install Node.js dependencies
RUN npm install

# Back to main code
WORKDIR /app

# Default command
CMD ["bash"]

```

**Comment by th-blitz** [comment]
Hi, 

Thank you for your time and support regarding this issue.
 
I encountered issues with `poetry install` on my local machine ( macOS, arm64 ), specifically with the installation of `uwsgi` and `scikit-learn`. However, the same process worked successfully on a Linux Docker image ( both arm64 and x86 architectures ).

To address this, I created a linux docker image, which allowed me to install the dependencies without errors. That said, I subsequently faced issues with `uwsgi` and `playwright` within the docker environment which will require further debugging ( I faced similar issues on a local setup after manually installing the dependencies ).

Given this workaround, I am closing this issue as of now. 
For reference, please find the `Dockerfile` I used in case it may prove helpful:

```dockerfile
# Pull debian linux ( bookworm )
FROM debian:bookworm

RUN apt-get update 
RUN apt-get upgrade -y

# Install build essential and other libraries
RUN apt install build-essential -y
RUN apt install zlib1g-dev
RUN apt install libncurses5-dev -y
RUN apt install libgdbm-dev
RUN apt install libnss3-dev -y
RUN apt install libssl-dev
RUN apt install libreadline-dev
RUN apt install libffi-dev
RUN apt install libpq-dev -y
RUN apt install wget -y
RUN apt install curl -y
RUN apt install git -y 

# install libraries needed for visualizations
RUN apt-get install ffmpeg libsm6 libxext6 -y

# Install node version manager ( nvm ) and use nvm to install node 17^
SHELL ["/bin/bash", "--login", "-i", "-c"]
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
RUN source /root/.bashrc && nvm install 17
SHELL ["/bin/bash", "--login", "-c"]

# Prepare for python installation
WORKDIR /home
RUN mkdir -p python
WORKDIR /home/python

# Pull official python version of 3.9.6 source code
RUN wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
RUN tar -xvf *.tgz
RUN rm *.tgz
WORKDIR /home/python/Python-3.9.6

# Build python from source
RUN ./configure --enable-optimizations
RUN make install 
RUN pip3 install virtualenv --no-cache-dir
RUN pip3 install requests --no-cache-dir
RUN pip3 install poetry --no-cache-dir

# Finally install uwsgi dependencies
RUN apt-get install libpcre3 libpcre3-dev -y
RUN apt-get install -y xvfb

# Install postgres sql
RUN apt-get install postgresql postgresql-contrib -y

# Install chrome ( requires x86 architecture or use an x86 emulator with docker ) 
WORKDIR /home
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y ./google-chrome-stable_current_amd64.deb

```
